mysql:
  image: mysql:5.7.17
  volumes:
    - /home/ds/tc10/mysql/data:/var/lib/mysql
    - ./configs/my.cnf:/etc/mysql/conf.d/my.cnf
  environment:
    - MYSQL_ROOT_PASSWORD=tc10PS
    - MYSQL_DATABASE=tc10
    - MYSQL_USER=tc10
    - MYSQL_PASSWORD=tc10

teamcity:
  image: jetbrains/teamcity-server:2017.1.2
  links: 
    - mysql
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/ds/tc10/teamcity/data:/data/teamcity_server/datadir
    - /home/ds/tc10/teamcity/logs:/opt/teamcity/logs
    - ./configs/server.xml:/opt/teamcity/conf/server.xml
    - ./entrypoint.sh:/entrypoint.sh
  environment:
    - TEAMCITY_CONTEXT=teamcities
    - TEAMCITY_DATA_PATH=/data/teamcity_server/datadir
    - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m
  entrypoint: /entrypoint.sh

teamcity_sjh:
  image: jetbrains/teamcity-server:2017.1.2
  links:
    - mysql
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/ds/teamcity_sjh/teamcity/data:/data/teamcity_server/datadir
    - /home/ds/teamcity_sjh/teamcity/logs:/opt/teamcity/logs
    - ./configs_sjh/server.xml:/opt/teamcity/conf/server.xml
    - ./configs_sjh/entrypoint.sh:/entrypoint.sh
  environment:
    - TEAMCITY_CONTEXT=tc-sjh
    - TEAMCITY_DATA_PATH=/data/teamcity_server/datadir
    - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m
  entrypoint: /entrypoint.sh



